#!/usr/bin/env python3
"""
wizard.py — interactive initial setup for whalesignal.

What it does:
  1) asks a few questions (telegram channel, etherscan key opt-in, etc)
  2) writes config.json with non-secret settings
  3) prints the EXACT `wrangler secret put` commands you need to run
     so that secrets never touch disk (you type values when wrangler prompts)

What it does NOT do:
  - store any API key or bot token on disk (those go in wrangler secrets)
  - deploy anything (use deploy_all.py)
  - run anything that costs cloudflare quota
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXAMPLE = HERE / "config.example.json"
OUT = HERE / "config.json"


def prompt(label, default=None, validate=None):
    suffix = f" [{default}]" if default != None else ""
    while True:
        v = input(f"{label}{suffix}: ").strip()
        if not v and default is not None:
            v = str(default)
        if not v:
            print("  ! required, can't be empty")
            continue
        if validate:
            ok, err = validate(v)
            if not ok:
                print(f"  ! {err}")
                continue
        return v


def confirm(label, default=True):
    d = "Y/n" if default else "y/N"
    v = input(f"{label} [{d}]: ").strip().lower()
    if not v:
        return default
    return v in ("y", "yes", "1", "true")


CHANNEL_RE = re.compile(r"^@[\w-]{3,64}$")


def channel_ok(v):
    if not CHANNEL_RE.match(v):
        return False, "channel must be @something (3-64 chars, [A-Za-z0-9_-])"
    return True, ""


def main():
    print("=" * 60)
    print("WhaleSignal setup wizard")
    print("=" * 60)
    print("I'll ask a few questions. After, you'll get the exact")
    print("`wrangler secret put ...` commands to run so keys never hit disk.")
    print()

    channel = prompt("Telegram public channel (with @)", validate=channel_ok)
    send_to_users_now = confirm("Allow DMs to the bot itself right now? "
                                "(routes you haven't built features for yet — recommend no)",
                                default=False)
    use_etherscan = confirm("Got a free etherscan API key? (improves rate "
                            "limits — recommended yes if you'll deploy for real)")
    use_cryptopanic = confirm("Got a CryptoPanic API token? (Phase 4 — "
                              "skip for Phase 1)", default=False)

    cfg = {
        "_comment": "Non-secret runtime config. Secrets go in wrangler via "
                    "`wrangler secret put`. Generated by wizard.py.",
        "cloudflare_names": {
            "d1_database": "whalesignal-db",
            "kv_namespace": "whalesignal-kv",
            "queue": "whalesignal-q",
            "queue_bot": "whalesignal-bot-q",
        },
        "thresholds": {
            "min_whale_usd": 500000,
            "max_blocks_per_scan": 10,
            "market_cache_ttl_seconds": 300,
            "news_cache_ttl_seconds": 3600,
        },
        "telegram_public_channel": channel,
        "use_etherscan_key": bool(use_etherscan),
        "use_cryptopanic": bool(use_cryptopanic),
    }
    OUT.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print(f"\n[ok] wrote non-secret config to {OUT}\n")

    print("=" * 60)
    print("Now run these (you'll type each value when wrangler prompts):")
    print("=" * 60)
    print()
    print("# --- REQUIRED ---")
    print("# Telegram bot token (from @BotFather):")
    print(f"npx wrangler secret put BOT_TOKEN  -c wrangler.bot.toml")
    print()
    print("# Gemini API key (https://aistudio.google.com/app/apikey):")
    print(f"npx wrangler secret put GEMINI_KEY  -c wrangler.analyst.toml")
    print()
    print("# Public channel name as a var (also set in wrangler.bot.toml [vars]):")
    print("# (NOT a secret — you already put it in config.json)")
    print(f"#    PUBLIC_CHANNEL = \"{channel}\"  <- already in wrangler.bot.toml [vars]")
    print()
    if use_etherscan:
        print("# --- RECOMMENDED ---")
        print("# Etherscan free key (https://etherscan.io/myapikey):")
        print(f"npx wrangler secret put ETHSCAN_KEY -c wrangler.scanner.toml")
        print()
    if use_cryptopanic:
        print("# --- PHASE 4 (optional now) ---")
        print("# CryptoPanic auth token (https://cryptopanic.com/developers/api/):")
        print(f"npx wrangler secret put CRYPTOPANIC_TOKEN -c wrangler.scanner.toml")
        print()
    print("=" * 60)
    print("Next steps:")
    print("=" * 60)
    print()
    print("  1. create the public channel in Telegram and add your bot as admin")
    print(f"     ({channel} — only the channel name is needed)")
    print("  2. run the secret commands above (you'll paste values when prompted)")
    print("  3. deploy everything:")
    print("       python deploy_all.py")
    print("  4. fleet the bot worker received a public URL after deploy.")
    print("     set the telegram webhook (deploy_all.py prints the exact URL):")
    print("       python deploy_all.py --set-webhook")
    print()
    print("  5. tail logs to verify the scanner is running:")
    print("       npx wrangler tail whalesignal-scanner")
    print()
    print("that's it. ping a whale. ∎")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\naborted by user — nothing written beyond what was already saved.")
        sys.exit(130)
