#!/usr/bin/env python3
"""
seed.py — load wallet_labels/exchanges.json into D1 `wallets` table.

Uses `npx wrangler d1 execute` so it runs against the real remote D1.
Idempotent: INSERT OR IGNORE on PRIMARY KEY (address, chain) means
re-running is safe and won't overwrite patterns/tx_count set later.

Usage:
    python wallet_labels/seed.py                  # uses DB_NAME from wrangler.toml
    python wallet_labels/seed.py --db whalesignal-db
    python wallet_labels/seed.py --dry-run         # print sql, don't run
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
EXCHANGES = HERE / "exchanges.json"
WRANGLER_TOML = REPO / "wrangler.toml"


def load_seed():
    if not EXCHANGES.exists():
        sys.exit(f"missing {EXCHANGES}")
    return json.loads(EXCHANGES.read_text(encoding="utf-8"))


def db_name_from_wrangler():
    """Pull the configured d1_databases name out of wrangler.toml. Best-effort."""
    if not WRANGLER_TOML.exists():
        return None
    name = None
    for line in WRANGLER_TOML.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("database_name") and "=" in s:
            name = s.split("=", 1)[1].strip().strip('"').strip("'")
    return name


def build_sql(data):
    lines = ["-- generated by wallet_labels/seed.py — do not edit by hand", "-- INSERT OR IGNORE so re-seeding will not clobber learned patterns/counts."]
    for chain in ("btc", "eth"):
        for row in data.get(chain, []):
            addr = row["address"]
            label = row["label"].replace("'", "''")
            typ = row.get("type", "exchange")
            lines.append(
                f"INSERT OR IGNORE INTO wallets (address, chain, label, type) "
                f"VALUES ('{addr}', '{chain}', '{label}', '{typ}');"
            )
    return "\n".join(lines)


def wrangler_exec(sql, db, dry_run=False):
    if dry_run:
        print("--- dry run, would execute via wrangler ---")
        print(sql)
        return 0
    print(f"[seed] applying SQL to D1 database '{db}' via wrangler...")
    res = subprocess.run(
        ["npx", "wrangler", "d1", "execute", db, "--remote", "--command", sql],
        cwd=REPO,
    )
    return res.returncode


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=None, help="D1 database name (default: from wrangler.toml)")
    ap.add_argument("--dry-run", action="store_true", help="print SQL only")
    args = ap.parse_args()

    data = load_seed()
    counts = {c: len(data.get(c, [])) for c in ("btc", "eth")}
    print(f"[seed] loaded {sum(counts.values())} wallet labels "
          f"(btc={counts['btc']} eth={counts['eth']}) from exchanges.json")

    sql = build_sql(data)

    db = args.db or db_name_from_wrangler()
    if not db:
        sys.exit("could not determine D1 database name. pass --db or set it in wrangler.toml")

    rc = wrangler_exec(sql, db, dry_run=args.dry_run)
    sys.exit(rc)


if __name__ == "__main__":
    main()
